### ISSUE TITLE
GitHub workflow: Tests are run twice on pull requests

### ISSUE THREAD

**Issue by carmenbianca** [OCA/oca-addons-repo-template#129]
## Module

All

## Describe the bug

The `test.yml` file contains the following text:

```yaml
on:
  pull_request:
    branches:
      - "15.0*"
  push:
    branches:
      - "15.0*"
```

and `pre-commit.yml` contains the following:

```yaml
on:
  pull_request:
  push:
```

Because of how GitHub workflows works, this creates two jobs for every commit: one for the pull request, and one for the push.

This is wasteful of resources.

## To Reproduce
**Affected versions**: Any module that uses GitHub workflows for CI

1. Create a PR against an OCA project that uses a GitHub workflow for tests.

Example: https://github.com/OCA/product-variant/pull/248

Duplicate runs of pre-commit:
- https://github.com/OCA/product-variant/runs/5317110166?check_suite_focus=true
- https://github.com/coopiteasy/product-variant/runs/5317109570?check_suite_focus=true

Duplicate runs of Odoo:
- https://github.com/OCA/product-variant/runs/5317110167?check_suite_focus=true
- https://github.com/coopiteasy/product-variant/runs/5317109857?check_suite_focus=true

**Expected behavior**
The test is only run once on either the push or the pull request.

**Additional context**
The following snippet is one way of fixing the problem:

```yaml
on:
  pull_request:
  push:
    branches:
      - "15.0"
```

This makes sure that all pull requests get run, and direct pushes to the main branch also get run. The only things that don't get run are commits made to a branch that doesn't have a PR, but I think that's fine.

Save the planet :earth_africa:

**Comment by legalsylvain** [comment]
:+1: thanks !

**Comment by carmenbianca** [comment]
@pedrobaeza This is not what this issue is about. The tests against Odoo get run twice, and the tests against OCB get run twice, for a total of four tests. We want that total down to two.

**Comment by carmenbianca** [comment]
Probably, I'm not sure, but even so I'd still classify this as a bug. There exists no scenario where the same commit should be tested in the exact same way twice.

**Comment by pedrobaeza** [comment]
Unfortunately, you have to comment that to GitHub, not to us. We need to have both pull request and push, as main OCA branches receive both type of things, and the CI should be done on them. Closing as no solution on our part. Meanwhile, just deactivate workflows on your fork (if possible), or put an issue on GitHub repo about that.

**Comment by carmenbianca** [comment]
I don't think I agree with that assessment. My proposed solution does what you describe. Are there pushes to the non-main branch that don't have a PR that must be run against CI?

**Comment by pedrobaeza** [comment]
When using the merge bot, the CI must be executed on the temporary generated branch for checking the rebased + extra commits CI

**Comment by carmenbianca** [comment]
But then you can do something like:

```yaml
on:
  pull_request:
  push:
    branches:
      - "15.0"
      - "*temporary_branch_identifier*"
```

I think there exists a solution here that isn't WONTFIX UPSTREAM.

**Comment by sbidoul** [comment]
I think this is worth some more discussion. How about this:

```yaml
on:
  pull_request:
    - "15.0*"
  push:
    branches:
      - "15.0"
      - "15.0-ocabot-*"
```

This would
- run on pull requests to any branch that start with 15.0 (which I sometime use on mis-builder to accumulate several PR in a big release branch)
- run on the main branches and ocabot branches
- let folks use the same pull-request based workflow on their own fork if they want to
