### ISSUE TITLE
Improve xml prettyfier

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-addons-repo-template#224]
prettier's xml pluggin now supports a much better XML autoformatting mode. See https://github.com/prettier/plugin-xml/issues/138#issuecomment-724547415.

Below are my findings on how to make it work.

You need a `.prettierrc.cjs` instead of `.prettierrc.yml`, so prettier can load the plugin even when run from pre-commit:

```javascript
/** @type {import('prettier').Config} */
const config = {
  plugins: [require.resolve("@prettier/plugin-xml")],
  bracketSpacing: false,
  printWidth: 88,
  proseWrap: "always",
  semi: true,
  trailingComma: "es5",
  xmlWhitespaceSensitivity: "preserve",
};

module.exports = config;
```

And the pre-commit config needs to be adapted like so:

```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: prettier + plugin-xml
        additional_dependencies:
          - "prettier@3.0.3"
          - "@prettier/plugin-xml@3.2.2"
```
