### ISSUE TITLE
Problem with eslint in oca/web v15 repository 

### ISSUE THREAD

**Issue by SplashS** [OCA/oca-addons-repo-template#85]
I have pre-commit failed in PR https://github.com/OCA/web/pull/2058
Link to build
https://github.com/OCA/web/runs/3997888875?check_suite_focus=true

There is problem with ESLint configuration.
Error that I've got:
`  5:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`

Locally I avoid this error with configuration patch to .eslintrc.yml:
```
parserOptions:
  ecmaVersion: 2017
  sourceType: module

overrides:
  - files:
    - "**/legacy/**/*.js"
    parserOptions:
      sourceType: script
```

Should I include this patch in oca/web PR or it can be made globally for all v15 repositories?
